export const LIGHTING_MODES = {
  game: "game",
  cinematic: "cinematic",
  night: "night",
};

export const LIGHTING_MODE_OPTIONS = [
  { value: LIGHTING_MODES.game, label: "Juego" },
  { value: LIGHTING_MODES.cinematic, label: "Cinematica" },
  { value: LIGHTING_MODES.night, label: "Noche" },
];

export const LIGHTING_PRESETS = {
  [LIGHTING_MODES.game]: {
    label: "Juego",
    description: "Luz clara y legible inspirada en Minecraft.",
    skyTop: "#8cc8ff",
    skyBottom: "#e9f5ff",
    fogColor: "#cfe7ff",
    ambientBase: 0.55,
    ambientRange: 0.22,
    hemisphereBase: 0.5,
    hemisphereRange: 0.2,
    directionalBase: 0.75,
    directionalRange: 0.55,
    shadowStrength: 1,
    warmTint: "#fff0c4",
    coolTint: "#cfe7ff",
    shadowMapSize: 2048,
  },
  [LIGHTING_MODES.cinematic]: {
    label: "Cinematica",
    description: "Mas contraste y profundidad para capturas.",
    skyTop: "#5f8fdc",
    skyBottom: "#f7cba2",
    fogColor: "#d9b99f",
    ambientBase: 0.35,
    ambientRange: 0.2,
    hemisphereBase: 0.35,
    hemisphereRange: 0.18,
    directionalBase: 1.0,
    directionalRange: 0.7,
    shadowStrength: 1.15,
    warmTint: "#ffd59a",
    coolTint: "#9cc7ff",
    shadowMapSize: 2048,
  },
  [LIGHTING_MODES.night]: {
    label: "Noche",
    description: "Ambiente nocturno visible, sin perder lectura.",
    skyTop: "#10192e",
    skyBottom: "#233454",
    fogColor: "#1a2840",
    ambientBase: 0.16,
    ambientRange: 0.1,
    hemisphereBase: 0.2,
    hemisphereRange: 0.08,
    directionalBase: 0.22,
    directionalRange: 0.2,
    shadowStrength: 0.55,
    warmTint: "#aac8ff",
    coolTint: "#5d83c8",
    shadowMapSize: 1024,
  },
};
